### ISSUE TITLE
Doesn't work with Python 3.11

### ISSUE THREAD

**Issue by dkadioglu** [pikim/script.service.kodi.callbacks#7]
On the Libreelec Nightly 181122 Kodi Callbacks doesn't work anymore and errors out with:

```
EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'AttributeError'>
                                                   Error Contents: module 'collections' has no attribute 'MutableSet'
                                                   Traceback (most recent call last):
                                                     File "/storage/.kodi/addons/script.service.kodi.callbacks/resources/lib/publishers/watchdog.py", line 26, in <module>
                                                       from .watchdog.observers import Observer
                                                   ModuleNotFoundError: No module named 'resources.lib.publishers.watchdog.observers'; 'resources.lib.publishers.watchdog' is not a package
                                                   
                                                   During handling of the above exception, another exception occurred:
                                                   
                                                   Traceback (most recent call last):
                                                     File "/storage/.kodi/addons/script.service.kodi.callbacks/default.py", line 39, in <module>
                                                       from resources.lib.publisherfactory import PublisherFactory
                                                     File "/storage/.kodi/addons/script.service.kodi.callbacks/resources/lib/publisherfactory.py", line 32, in <module>
                                                       from resources.lib.publishers.watchdog import WatchdogPublisher
                                                     File "/storage/.kodi/addons/script.service.kodi.callbacks/resources/lib/publishers/watchdog.py", line 34, in <module>
                                                       from resources.lib.watchdog.observers import Observer
                                                     File "/storage/.kodi/addons/script.service.kodi.callbacks/resources/lib/watchdog/observers/__init__.py", line 69, in <module>
                                                       from .inotify import InotifyObserver as Observer
                                                     File "/storage/.kodi/addons/script.service.kodi.callbacks/resources/lib/watchdog/observers/inotify.py", line 74, in <module>
                                                       from .inotify_buffer import InotifyBuffer
                                                     File "/storage/.kodi/addons/script.service.kodi.callbacks/resources/lib/watchdog/observers/inotify_buffer.py", line 20, in <module>
                                                       from watchdog.observers.inotify_c import Inotify
                                                     File "/storage/.kodi/addons/script.service.kodi.callbacks/resources/lib/watchdog/observers/__init__.py", line 69, in <module>
                                                       from .inotify import InotifyObserver as Observer
                                                     File "/storage/.kodi/addons/script.service.kodi.callbacks/resources/lib/watchdog/observers/inotify.py", line 76, in <module>
                                                       from watchdog.observers.api import (
                                                     File "/storage/.kodi/addons/script.service.kodi.callbacks/resources/lib/watchdog/observers/api.py", line 23, in <module>
                                                       from watchdog.utils.bricks import SkipRepeatsQueue
                                                     File "/storage/.kodi/addons/script.service.kodi.callbacks/resources/lib/watchdog/utils/bricks.py", line 175, in <module>
                                                       class OrderedSet(collections.MutableSet):
                                                                        ^^^^^^^^^^^^^^^^^^^^^^
                                                   AttributeError: module 'collections' has no attribute 'MutableSet'
                                                   -->End of Python script error report<--
```
This seems to happen because of the recent switch to Python 3.11.
I found this which might be related and help:
https://www.datasciencelearner.com/attributeerror-module-collections-has-no-attribute-mutablemapping/

**Comment by dkadioglu** [comment]
Found a simple workaround (or fix?):
In the file script.service.kodi.callbacks/resources/lib/watchdog/utils/bricks.py just add these two lines after `import collections`:
```
from collections import abc
collections.MutableSet = abc.MutableSet
```
